#!/usr/bin/env bash
SCRIPTS_DIR="$(cd "$(dirname "$0")/../scripts" && pwd)"
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT
cd "$TMP"
git init -q
git -c user.name=test -c user.email=test@example.com commit -q --allow-empty -m base
mkdir -p bin .verify

cat > bin/curl << 'MOCK'
#!/usr/bin/env bash
echo '<html>healthy</html>'
MOCK
chmod +x bin/curl
export PATH="$TMP/bin:$PATH"

cat > .verify/setup.json << 'JSON'
{"mode":"none","compose_file":null,"boot":"","teardown":"","seed":[],
 "seed_data_files":[],"health_url":"","base_url":"http://localhost:9","env_file":"",
 "observe":{},"probes":{"sink":"false","worker":"","storage":""}}
JSON
cat > .verify/plan.json << 'JSON'
{"slug":"pipeline-e2e","criteria":[
 {"id":"ac-pass","description":"healthy path proves the new behavior","url":"/","steps":[],"screenshot_at":[],"depends_on":["api"],"proof":{"kind":"marker-in-data","detail":"agent log row"},"guards":"new-behavior"},
 {"id":"ac-sink","description":"message reaches sink","url":"/","steps":[],"screenshot_at":[],"depends_on":["sink"],"proof":{"kind":"marker-in-data","detail":"sink message"},"guards":"new-behavior"},
 {"id":"ac-omitted","description":"judge must cover every plan item","url":"/","steps":[],"screenshot_at":[],"depends_on":["api"],"proof":{"kind":"live-read","detail":"fresh response"},"guards":"existing-behavior"},
 {"id":"ac-worker","description":"worker result exists","url":"/","steps":[],"screenshot_at":[],"depends_on":["worker"],"proof":{"kind":"marker-in-data","detail":"job row"},"guards":"new-behavior"}
],"skipped":[],"seed_plan":[{"description":"create marked fixture","via":"POST /fixtures"}]}
JSON
cat > .verify/seed.sh << 'SEED'
#!/usr/bin/env bash
# Generated by /verify from the approved seed plan. Reviewed at approval.
# $1 = this run's marker. Every entity created must carry it.
set -euo pipefail
MARKER="${1:?usage: seed.sh <marker>}"
BASE_URL="${VERIFY_BASE_URL:?}"
echo "$MARKER" | tee -a seeded-markers.log
SEED
chmod +x .verify/seed.sh

MOCK_CLAUDE="$TMP/mock-judge"
cat > "$MOCK_CLAUDE" << 'MOCK'
#!/usr/bin/env bash
cat > /dev/null
echo called >> judge-calls.log
cat << 'JSON'
{"verdict":"pass","summary":"wrong","criteria":[
 {"ac_id":"ac-pass","status":"pass","proof_seen":true,"did":"posted marked fixture","observed":"marker row returned","reasoning":"marker proved the run","evidence":".verify/evidence/ac-pass/agent.log"},
 {"ac_id":"ac-sink","status":"could_not_verify","proof_seen":false,"did":"","observed":"","reasoning":"sink down","evidence":".verify/evidence/prechecks/sink.log"},
 {"ac_id":"ac-worker","status":"fail","proof_seen":false,"did":"queued marked job","observed":"no job row","reasoning":"worker result missing","evidence":".verify/evidence/ac-worker/agent.log"}
]}
JSON
MOCK
chmod +x "$MOCK_CLAUDE"

"$SCRIPTS_DIR/env.sh" up
RUN_ID=$(jq -r '.run_id' .verify/run-env.json)
RUN_DIR=".verify/runs/$RUN_ID"
MARKER=$(jq -r '.marker' .verify/run-env.json)
"$SCRIPTS_DIR/env.sh" seed
cp .verify/seed.sh "$RUN_DIR/seed.sh"
VERIFY_BASE_URL="http://localhost:9" bash .verify/seed.sh "$MARKER" 2>&1 | tee "$RUN_DIR/seed.log"
"$SCRIPTS_DIR/precheck.sh"
mkdir -p .verify/evidence/{ac-pass,ac-sink,ac-omitted,ac-worker}
printf 'VERDICT: pass\nREASONING: row %s\n' "$MARKER" > .verify/evidence/ac-pass/agent.log
printf "COULD_NOT_VERIFY: dependent part 'sink' failed its pipeline check\n" > .verify/evidence/ac-sink/agent.log
printf 'VERDICT: pass\nREASONING: fresh response %s\n' "$MARKER" > .verify/evidence/ac-omitted/agent.log
printf 'VERDICT: fail\nREASONING: no job row for %s\n' "$MARKER" > .verify/evidence/ac-worker/agent.log
VERIFY_ALLOW_DANGEROUS=1 CLAUDE_BIN="$MOCK_CLAUDE" "$SCRIPTS_DIR/judge.sh"
"$SCRIPTS_DIR/report.sh" > /dev/null

jq -e '.marker | startswith("verify-")' .verify/run-env.json > /dev/null || { echo "FAIL: marker missing"; exit 1; }
grep -q "$MARKER" seeded-markers.log || { echo "FAIL: seed script did not receive marker"; exit 1; }
grep -q "$MARKER" "$RUN_DIR/seed.log" || { echo "FAIL: seed log lacks marker"; exit 1; }
[ -f "$RUN_DIR/seed.sh" ] || { echo "FAIL: run folder lacks seed script"; exit 1; }
[ "$(jq -r '.tainted["ac-sink"]' .verify/precheck.json)" = "sink" ] || { echo "FAIL: sink AC not tainted"; exit 1; }
jq -e '.unchecked | index("worker") != null' .verify/precheck.json > /dev/null || { echo "FAIL: worker not unchecked"; exit 1; }
[ "$(jq -r '.criteria[] | select(.ac_id=="ac-sink") | .status' .verify/report.json)" = "could_not_verify" ] || { echo "FAIL: sink status"; exit 1; }
[ "$(jq -r '.criteria[] | select(.ac_id=="ac-omitted") | .status' .verify/report.json)" = "not_proven" ] || { echo "FAIL: omitted status"; exit 1; }
[ "$(jq -r '.verdict' .verify/report.json)" != "pass" ] || { echo "FAIL: wrong judge verdict trusted"; exit 1; }
[ "$(jq 'length' "$RUN_DIR/canonical.json")" = "4" ] || { echo "FAIL: canonical count"; exit 1; }
grep -q '1 of 4 proven' "$RUN_DIR/report.html" || { echo "FAIL: report headline"; exit 1; }
grep -qE '<h1[^>]*>PASS' "$RUN_DIR/report.html" && { echo "FAIL: report incorrectly says PASS"; exit 1; }
grep -q 'may be environmental' "$RUN_DIR/report.html" || { echo "FAIL: worker environmental note"; exit 1; }

# A second run with a failing approved seed script must never reach the judge.
cat > .verify/seed.sh << 'SEED'
#!/usr/bin/env bash
set -euo pipefail
exit 1
SEED
set +e
(
  set -e
  "$SCRIPTS_DIR/env.sh" up
  trap '"$SCRIPTS_DIR/env.sh" down' EXIT
  MARKER2=$(jq -r '.marker' .verify/run-env.json)
  VERIFY_BASE_URL="http://localhost:9" bash .verify/seed.sh "$MARKER2"
  VERIFY_ALLOW_DANGEROUS=1 CLAUDE_BIN="$MOCK_CLAUDE" "$SCRIPTS_DIR/judge.sh"
)
SEED_RUN_CODE=$?
set -e
if [ "$SEED_RUN_CODE" -eq 0 ]; then
  echo "FAIL: failing seed script should abort"
  exit 1
fi
[ "$(wc -l < judge-calls.log)" = "1" ] || { echo "FAIL: judge ran after seed failure"; exit 1; }

echo "PASS: pipeline e2e tests"
